package pubfinder.pubfinder.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pubfinder.pubfinder.db.Pub;

import pubfinder.pubfinder.db.PubDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pubDaoConfig;

    private final PubDao pubDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pubDaoConfig = daoConfigMap.get(PubDao.class).clone();
        pubDaoConfig.initIdentityScope(type);

        pubDao = new PubDao(pubDaoConfig, this);

        registerDao(Pub.class, pubDao);
    }
    
    public void clear() {
        pubDaoConfig.getIdentityScope().clear();
    }

    public PubDao getPubDao() {
        return pubDao;
    }

}
