package pubfinder.pubfinder.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PUB".
 */
public class Pub {

    private Long id;
    private String name;
    private String address;
    private String music;

    public Pub() {
    }

    public Pub(Long id) {
        this.id = id;
    }

    public Pub(Long id, String name, String address, String music) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.music = music;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMusic() {
        return music;
    }

    public void setMusic(String music) {
        this.music = music;
    }

}
